# SPDX-License-Identifier: GPL-2.0
TEST_GEN_PROGS := unmounted_tree_test overmount_reparent_test
TEST_GEN_PROGS += nsfs_rbind_loop_test overmount_ns_file_test

CFLAGS += -Wall -O2 -g $(KHDR_INCLUDES)

include ../../lib.mk
